package me.hatter.tools.taskprocess.util.concurrent.exception;

public interface ExceptionHandler {

    void handle(Exception e);
}
